# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 05:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.EmailField(db_index=True, max_length=254)),
                ('from_email', models.EmailField(max_length=254)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('html_body', models.TextField(blank=True, null=True)),
                ('plain_body', models.TextField(blank=True, null=True)),
                ('subject', models.TextField()),
                ('uuid', models.CharField(default=uuid.uuid4, max_length=36, unique=True)),
            ],
        ),
    ]
